spring:
  application:
    name: ambev_order

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
    
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: validate

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Sao_Paulo

  kafka:
    bootstrap-servers: localhost:9092

  threads:
    virtual:
      enabled: true

  flyway:
    enabled: true

server:
  port: 8080